---
# "pre-commit run --files example.yml" to check a file
ci:
  # format compatible with commitlint
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
  autofix_commit_msg: |
    chore: auto fixes from pre-commit.com hooks
# https://cspell.org/docs/getting-started/
# default_language_version:
#     python: python3.11
repos:
  # Self defined hook to replace ß with ss
  - repo: local
    hooks:
      - id: replace-ß
        name: Replace ß with ss
        entry: sed -i '' 's/ß/ss/g'    # s=substitute, g=global(not just first)
        language: system
        exclude: ^(\.pre-commit-config.yaml|docs/03_Service/CSpell.md|docs/03_Service/pre-commit.md|.*\.png)$
  # Hook for spell checking with cspell config file cspell.config.yaml
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.15.2
    hooks:
      - id: cspell
        args: [--relative, --no-progress, --no-summary]
        name: Spell check with cspell
        # files: \.(md|txt|py|js|ts|html|css|json)$
  # Pre-commit hooks for checking code style
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace           # Trims trailing whitespace
      - id: end-of-file-fixer             # Ensure files end with a newline
      - id: check-case-conflict           # Check for files with names that differ only in case
      - id: check-illegal-windows-names   # Check for files with illegal windows filenames
      - id: check-symlinks                # Check for symlinks which are broken
      - id: check-yaml                    # Check yaml files for syntax errors
  # Check if commit messages are formatted correctly
  - repo: https://github.com/Woile/commitizen
    rev: v3.30.0
    hooks:
      - id: commitizen
        stages: [commit-msg]
  #  exclude line from yamllint with following command on the end -> # yamllint disable-line
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          [
            "-d {extends: relaxed, rules: {line-length: {max: 120}}}",
            "-s",
          ]
        files: \.(yaml|yml)$
        exclude: Playbooks_OLD/.*
