---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  # - repo: https://github.com/adrienverge/yamllint
  #   rev: v1.26.3
  #   hooks:
  #     - id: yamllint
  # - repo: https://github.com/pre-commit/mirrors-prettier  # code formatter
  #   rev: v2.5.1
  #   hooks:
  #     - id: prettier
  - repo: https://github.com/codespell-project/codespell    # checks for typos.
    rev: v2.1.0
    hooks:
      - id: codespell
  - repo: https://github.com/Woile/commitizen     # Check if commit messages are formatted correctly
    rev: v2.20.3
    hooks:
      - id: commitizen
        stages: [commit-msg]
