---
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  # Use `cspell-cli trace word` to check where a work is defined
  # - en_US
  # https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/de_DE/README.md
  # Add Environment variable: C:\Users\%Username%\AppData\Roaming\npm  -> restart cmd
  - de_de
  - bash
  - words
  - html
  - python
ignorePaths:
  - cspell.config.yaml
  - pre-commit-config.yaml
  # Other
  - "*.svg"
