---
# https://cspell.org/docs/dictionaries-custom/
dictionaryDefinitions:
  - name: words
    path: .config/dictionary.txt
    addWords: true
dictionaries:
  # Use `cspell-cli trace word` to check where a work is defined
  # https://github.com/streetsidesoftware/cspell-dicts/blob/main/dictionaries/de_DE/README.md
  - en_US
  - de_de
  - bash
  - words
  - html
  - python
ignorePaths:
  - cspell.config.yaml
  - pre-commit-config.yaml
  - _config.yml
  - "*.svg"

# https://cspell.org/configuration/patterns/#patterns
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - /ß/
